shutdown:
  entire-service-enabled: true

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1434;database=test;schema=dbo
    username: sa
    password: Strong!Passw0rd
    hikari:
      connection-test-query: SELECT 1

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  security:
    user:
      name: admin
      password: admin

  flyway:
    enabled: true

server:
  tomcat:
    max-threads: 10
    max-connections: 100
    min-spare-threads: 4
