spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306?database?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    hikari:
      connection-test-query: SELECT 1

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  security:
    user:
      name: admin
      password: admin

server:
  tomcat:
    max-threads: 10
    max-connections: 100
    min-spare-threads: 4
